import Navbar from "@/components/common/Navbar/Navbar";
// import { Temp } from "@/components/temp";
import "./globals.css";

export const metadata = {
  title: "Invent Lift",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {/* <Temp /> */}
        {children}
      </body>
    </html>
  );
}
