import "./globals.css";
import { Toaster } from 'react-hot-toast';
import { Poppins } from 'next/font/google';

export const metadata = {
  title: "Invent Lift",
  description: "Generated by create next app",
};


const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
      <Toaster 
          position="top-right"
          toastOptions={{
            duration: 3000,
            style: {
              background: '#363636',
              color: '#fff',
            },
          }}
        />
        {children}
      </body>
    </html>
  );
}
